### ISSUE TITLE
Add history_rbt

### ISSUE THREAD

**Issue by estellerv** [ABRBABY/ABRBABY_matlab#11]
@annesodub Could you please create a history_rbt (rbt for "reject bad trials") variable as you did for history_rfe ?
This variable should appear in the 'select_and_save_trials_per_condition' function, and be initialized in the main script for ERPs ('main_abrbaby_ERP'). In consequence, the 'reject_trials_produce_report' function should be modified so it takes the OPTION structure as an input to create the report on rejected trials.
Thanks!

**Comment by annesodub** [comment]
done?

**Comment by estellerv** [comment]
Done!
