### ISSUE TITLE
Write a function to convert the visually inspected .set into -> trial_description.txt

### ISSUE THREAD

**Issue by annesodub** [ABRBABY/ABRBABY_matlab#80]
@estellerv : je vais ecrire une fonction permattant d'extraire les indices des mauvais essais à partir d'un jeu de données tel que ceux sur lesquels Clem a rejeté des essais. Peux-tu m'envoyer un exemple de données stp? (elsewhere filez, amubox) merci de m'envoyer le lien sur cette issue. 

A+
AnneSo

**Comment by estellerv** [comment]
@annesodub J'ai déjà créé une fonction qui fait ça, je la mets en PJ dans un .txt et en format Maltab dans le dossier qui contient le jeu de données pour exemple (cf ci-dessous) si jamais tu veux t'en inspirer.

[save_rejected_events_indices_by_condition.txt](https://github.com/ABRBABY/ABRBABY_matlab/files/14054045/save_rejected_events_indices_by_condition.txt)
 
Voici un dossier avec un jeu de données pour exemple avec deux participants : https://amubox.univ-amu.fr/s/fatEK9n9jJ4AD4K
(Sinon tu peux le trouver directement via ton AmuBox via : Projet-ABRbaby\Data\example_manual_rejection)

A+
